services:
  php:
    image: php:8.3-apache
    container_name: portfolio
    ports:
      - "8001:80" # on définit le port pour accéder à l'application sur la première valeur (localhost:8000 si on a 8000:80)
    volumes:
      - ./src:/var/www/html # on monte le dossier courant dans le dossier /var/www/html du container
    build:
      context: .
      dockerfile: Dockerfile

  db_infinitea:
    image: mysql:8.0
    container_name: infinitea_mysql8_0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: infinitea # nom de la base de données
      MYSQL_USER: infinitea
      MYSQL_PASSWORD: infinitea_password
    volumes:
      - "./data/infinitea:/docker-entrypoint-initdb.d" # Monte tout le dossier contenant les fichiers SQL pour infinitea
    ports:
      - "3365:3306" # Expose le port 3306 de MySQL sur le port 3365 de l'hôte

  db_elsan:
    image: mysql:8.0
    container_name: elsan_mysql8_0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elsan # nom de la base de données
      MYSQL_USER: elsan_admin
      MYSQL_PASSWORD: elsan_password
    volumes:
      - "./data/elsan:/docker-entrypoint-initdb.d" # Monte tout le dossier contenant les fichiers SQL pour elsan
    ports:
      - "3366:3306" # Expose le port 3306 de MySQL sur le port 3366 de l'hôte

  phpma_infinitea:
    image: phpmyadmin/phpmyadmin
    container_name: portfolio_phpmyadmin_infinitea
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db_infinitea  # Connexion au service db_infinitea
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 20M
    ports:
      - "8082:80"  # Accès à phpMyAdmin pour Infinitea (localhost:8082)

  phpma_elsan:
    image: phpmyadmin/phpmyadmin
    container_name: portfolio_phpmyadmin_elsan
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db_elsan  # Connexion au service db_elsan
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 20M
    ports:
      - "8081:80"  # Accès à phpMyAdmin pour Elsan (localhost:8081)